run:
  num_dataloader_workers: 0
  batch_size: 32
  world_size: 1
  save_path: src/upstream/delores_m/

pretrain:
  base_encoder:       # options are ....
    type:  AudioNTT2020Task6
    output_dim: 2048
    return_all_layers: True
  projection_dim: 2048
  contrastive_dim: 128
  normalization: mean_var               # options mean_var (zero mean and unit variance) or l2
  lambda_barlow: [5e-5,5e-5,5e-5]
  loss_scale: 1/32
  input:
    type: raw_wav                       # options are raw_wav or mel spectrogram
    sampling_rate: 16000                # the sampling rate of your audio; please maintain one sampling rate
    length_wave: 0.95
    n_mels: 64
  augmentations:
    MixupBYOLA:
      ratio: 0.4
      log_mixup_exp: True
    Kmix:
      ratio: 0.4
      log_mixup_exp: True
      top_k: 128
      centroid_path: None
    PatchDrop:
      ratio: 0.3  
    RandomResizeCrop:
      virtual_crop_scale: [1.0,1.5]
      freq_crop_scale: [0.6,1.5]
      time_crop_scale: [0.6,1.5]


